### PR TITLE
Incorporate `moveit_experimental` and resurrect CHOMP

### PR DESCRIPTION
**Pull request by jbohren**
This adds @jrgnicho's updated `moveit_experimental` package (THANK YOU) and my migration of CHOMP to the latest MoveIt APIs. Also this catkinizes CHOMP (still missing install targets, though).

### CODE REVIEW

**Comment by davetcoleman** [comment]
This is awesome, can't wait to get this functionality back into MoveIt! main. However this ``moveit`` repo is experimental and I plan to force-push over it as the exact details of the merge are figured out and on the final "merge" day right before this becomes the master repo. I think this would be better if it were merged into kinetic branches on the old (current) repo setup.

Also would it be hard to split this PR into moveit_planner and moveit_experimental pieces?

**Comment by jbohren** [comment]
> This is awesome, can't wait to get this functionality back into MoveIt! main. However this moveit repo is experimental and I plan to force-push over it as the exact details of the merge are figured out and on the final "merge" day right before this becomes the master repo. I think this would be better if it were merged into kinetic branches on the old (current) repo setup.

Ah, got it. No worries. I was just excited at the prospect of not having tons of individual moveit repos checked out in my workspace.

> Also would it be hard to split this PR into moveit_planner and moveit_experimental pieces?

It's pretty easy. The `moveit_planners` stuff is just the current `moveit_planners` + my CHOMP fixes (http://github.com/jhu-lcsr-forks/moveit_planners). The `moveit_experimental` stuff is just @jrgnicho's current `moveit_experimental` fork (http://github.com/jrgnicho/moveit_experimental).

**Comment by davetcoleman** [comment]
Could you voice your support for the merge here?
http://discourse.ros.org/t/migration-to-one-github-repo-for-moveit/266/18

**Comment by jrgnicho** [comment]
FYI, the changes I made to that  [moveit_experimental fork](https://github.com/jrgnicho/moveit_experimental) didn't fix much beyond catkinizing.  Eventually, we copied this repo into [industrial_moveit](https://raesgit.datasys.swri.edu/raes-client/industrial_moveit/tree/indigo-devel/moveit_experimental) and continued developing there.

**Comment by davetcoleman** [comment]
It would be great to have a catkinized moveit_experimental. Also we should talk about how to merged industrial_moveit changes back into the main moveit

**Comment by jbohren** [comment]
@jrgnicho That's good to know. I'll base my work off of https://github.com/ros-industrial/industrial_moveit

**Comment by jrgnicho** [comment]
@davetcoleman , yes we'd be glad to support that.
@jbohren We'll be pushing some changes into the _moveit_experimental_ package in _industrial moveit_ soon.  
What's the plan moving forward for the _moveit_experimental_ code? How will the code there be promoted into a non-experimental package?

**Comment by davetcoleman** [comment]
as far as i can tell it does not bring in any crazy dependencies, so perhaps it should be merged into the upcoming unified moveit repo - i like that idea a lot

**Comment by jbohren** [comment]
> as far as i can tell it does not bring in any crazy dependencies, so perhaps it should be merged into the upcoming unified moveit repo - i like that idea a lot

Yeah that'd be good. That will also enable CHOMP and STOMP can be integrated into that too.

**Comment by davetcoleman** [comment]
I'd say go ahead and create a PR to moveit_experiemental and I'll review. I'll also add it to the merge script for future one-repo integration.

**Comment by davetcoleman** [comment]
Doesn't affect anything right now, but I've added the old moveit_experimental to this repo:

https://github.com/davetcoleman/moveit/tree/kinetic-devel/moveit_experimental

**Pull request closed without merging**
